import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/marathon.dart';

// 마라톤 목록 Provider (전역 상태 관리)
final marathonProvider = Provider<List<Marathon>>((ref) {
  // Mock data - 실제로는 API나 로컬 DB에서 가져옴
  return [
    Marathon(
      id: 'tokyo-2026',
      name: '도쿄 마라톤 2026',
      location: '일본 도쿄',
      date: DateTime(2026, 3, 1),
      regDate: '2025.08 접수 시작',
      distance: ['풀'],
      entryMethod: EntryMethod.lottery,
      difficulty: Difficulty.beginner,
      suitability: 5,
      accessibility: '직항',
      jetLag: '시차 없음',
      accommodation: '신주쿠/긴자 인근 추천',
      image:
          'https://images.unsplash.com/photo-1736086501687-6666b5b742bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2t5byUyMGNpdHklMjBzdHJlZXQlMjBydW5uaW5nfGVufDF8fHx8MTc3MDAzNzcyM3ww',
      tags: ['첫 해외 마라톤', '한국인 많이 가는 대회', '접근성 최고'],
      visaInfo: '무비자 (90일 체류 가능)',
      officialUrl: 'https://www.marathon.tokyo/',
    ),
    Marathon(
      id: 'berlin-2026',
      name: '베를린 마라톤 2026',
      location: '독일 베를린',
      date: DateTime(2026, 9, 27),
      regDate: '2025.10 추첨 접수',
      distance: ['풀'],
      entryMethod: EntryMethod.lottery,
      difficulty: Difficulty.advanced,
      suitability: 4,
      accessibility: '경유',
      jetLag: '7시간 (서머타임)',
      accommodation: '포츠담 광장 인근',
      image:
          'https://images.unsplash.com/photo-1756217600441-5c7be349f3ac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZXJsaW4lMjBtYXJhdGhvbiUyMGZpbmlzaCUyMGxpbmV8ZW58MXx8fHwxNzcwMDM3NzIwfDA',
      tags: ['PB 노리기 좋은 코스', '세계 6대 마라톤'],
      visaInfo: '무비자 (쉥겐 협정 90일)',
      officialUrl: 'https://www.bmw-berlin-marathon.com/',
    ),
    Marathon(
      id: 'london-2026',
      name: '런던 마라톤 2026',
      location: '영국 런던',
      date: DateTime(2026, 4, 26),
      regDate: '2025.04 추첨 마감',
      distance: ['풀'],
      entryMethod: EntryMethod.lottery,
      difficulty: Difficulty.intermediate,
      suitability: 3,
      accessibility: '직항',
      jetLag: '9시간',
      accommodation: '그리니치/카나리 워프',
      image:
          'https://images.unsplash.com/photo-1666350381413-0367f187b275?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsb25kb24lMjBtYXJhdGhvbiUyMHJ1bm5lcnMlMjB0b3dlciUyMGJyaWRnZXxlbnwxfHx8fDE3NzAwMzc3MjB8MA',
      tags: ['여행 겸용', '응원 열기 최고'],
      visaInfo: '무비자 (6개월 체류 가능)',
      officialUrl: 'https://www.tcslondonmarathon.com/',
    ),
    Marathon(
      id: 'osaka-2026',
      name: '오사카 마라톤 2026',
      location: '일본 오사카',
      date: DateTime(2026, 2, 22),
      regDate: '2025.08 접수 시작',
      distance: ['풀'],
      entryMethod: EntryMethod.lottery,
      difficulty: Difficulty.beginner,
      suitability: 5,
      accessibility: '직항',
      jetLag: '시차 없음',
      accommodation: '난바/오사카성 주변',
      image:
          'https://images.unsplash.com/photo-1590233464442-553fd33fca1a?auto=format&fit=crop&q=80&w=800',
      tags: ['첫 해외 마라톤', '먹방 여행', '기록컷 없음'],
      visaInfo: '무비자 (90일 체류 가능)',
      officialUrl: 'https://www.osaka-marathon.com/',
    ),
    Marathon(
      id: 'goldcoast-2026',
      name: '골드코스트 마라톤 2026',
      location: '호주 골드코스트',
      date: DateTime(2026, 7, 5),
      regDate: '2026.01 선착순',
      distance: ['풀', '하프', '10K'],
      entryMethod: EntryMethod.firstCome,
      difficulty: Difficulty.advanced,
      suitability: 4,
      accessibility: '경유',
      jetLag: '1시간',
      accommodation: '서퍼스 파라다이스',
      image:
          'https://images.unsplash.com/photo-1545044846-351ba102b4d5?auto=format&fit=crop&q=80&w=800',
      tags: ['PB 노리기 좋은 코스', '겨울 러닝', '가족 여행'],
      visaInfo: 'ETA 사전 승인 필수',
      officialUrl: 'https://goldcoastmarathon.com.au/',
    ),
  ];
});
