// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:marathon_flutter/models/marathon.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DifficultyAdapter());
    registerAdapter(EntryMethodAdapter());
    registerAdapter(MarathonAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DifficultyAdapter());
    registerAdapter(EntryMethodAdapter());
    registerAdapter(MarathonAdapter());
  }
}
